//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusData
    {
        public int Id { get; set; }
        public double Actual_Longitude { get; set; }
        public double Actual_Latitude { get; set; }
        public System.DateTime Measurement_Timestamp { get; set; }
        public double Actual_Speed { get; set; }
        public string BusId { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
