//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusDBEntities : DbContext
    {
        public BusDBEntities()
            : base("name=BusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusData> BusDatas { get; set; }
        public virtual DbSet<BusDriverData> BusDriverDatas { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<BusPosition> BusPositions { get; set; }
        public virtual DbSet<BusTrace> BusTraces { get; set; }
        public virtual DbSet<CarData> CarDatas { get; set; }
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<MeasuredData> MeasuredDatas { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<SimulatedBu> SimulatedBus { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
    }
}
