//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusDBlatestEntities : DbContext
    {
        public BusDBlatestEntities()
            : base("name=BusDBlatestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusData> BusData { get; set; }
        public virtual DbSet<BusDriverData> BusDriverData { get; set; }
        public virtual DbSet<Buses> Buses { get; set; }
        public virtual DbSet<BusPositions> BusPositions { get; set; }
        public virtual DbSet<BusTrace> BusTrace { get; set; }
        public virtual DbSet<CarData> CarData { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<MeasuredData> MeasuredData { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<References> References { get; set; }
        public virtual DbSet<SimulatedBus> SimulatedBus { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
    
        public virtual int arrivalTime(string busID, Nullable<int> stationID, ObjectParameter time_needed)
        {
            var busIDParameter = busID != null ?
                new ObjectParameter("busID", busID) :
                new ObjectParameter("busID", typeof(string));
    
            var stationIDParameter = stationID.HasValue ?
                new ObjectParameter("stationID", stationID) :
                new ObjectParameter("stationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("arrivalTime", busIDParameter, stationIDParameter, time_needed);
        }
    
        public virtual int simulateBus(string busID)
        {
            var busIDParameter = busID != null ?
                new ObjectParameter("busID", busID) :
                new ObjectParameter("busID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("simulateBus", busIDParameter);
        }
    
        public virtual int stationSchedule(Nullable<int> stationID)
        {
            var stationIDParameter = stationID.HasValue ?
                new ObjectParameter("stationID", stationID) :
                new ObjectParameter("stationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stationSchedule", stationIDParameter);
        }
    }
}
