//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int id { get; set; }
        public int busNr { get; set; }
        public System.TimeSpan startTime { get; set; }
        public int stationID { get; set; }
        public int weekday { get; set; }
    }
}
